### ISSUE TITLE
java.lang.ExceptionInInitializerError due to Scala module 2.9.10 requires Jackson Databind version >= 2.9.0 and < 2.10.0

### ISSUE THREAD

**Issue by AlexITC** [olafurpg/sbt-ci-release#167]
I'm setting up a library to be published by sbt-ci-relesae with github actions, I have done this previously for another project with success, now, I get an error I haven't been able to resolve by re-running the job, and I wonder if there is something else I should do ([project's repo](https://github.com/wiringbits/sjs-material-ui-facade)):

```
[info] Reapplying settings...
[info] set current project to sjs-material-ui-facade (in build file:/home/runner/work/sjs-material-ui-facade/sjs-material-ui-facade/)
2020-12-19 19:50:15.774Z  info [finagle] Using bridged scheduler with 2 workers 
2020-12-19 19:50:15.781Z  info [finagle] Finagle version 20.3.0 (rev=e3fd6d1bd88c9ed7edeb98a6598e23800924c633) built at 20200308-110321 
java.lang.ExceptionInInitializerError
	at com.twitter.finagle.toggle.StandardToggleMap$.loadJsonConfigWithEnv(StandardToggleMap.scala:187)
	at com.twitter.finagle.toggle.StandardToggleMap$.loadJsonConfig(StandardToggleMap.scala:127)
	at com.twitter.finagle.toggle.StandardToggleMap$.apply(StandardToggleMap.scala:100)
	at com.twitter.finagle.toggle.StandardToggleMap$.apply(StandardToggleMap.scala:85)
	at com.twitter.finagle.http.package$.<init>(package.scala:18)
	at com.twitter.finagle.http.package$.<clinit>(package.scala)
	at com.twitter.finagle.Http$useH2$.<init>(Http.scala:49)
	at com.twitter.finagle.Http$useH2$.<clinit>(Http.scala)
	at com.twitter.finagle.Http$Client.newClient(Http.scala:345)
	at com.twitter.finagle.client.EndpointerStackClient.newService(EndpointerStackClient.scala:148)
	at com.twitter.finagle.client.EndpointerStackClient.newService$(EndpointerStackClient.scala:145)
	at com.twitter.finagle.Http$Client.newService(Http.scala:171)
	at com.twitter.finagle.Client.newService(Client.scala:43)
	at com.twitter.finagle.Client.newService$(Client.scala:41)
	at com.twitter.finagle.Http$Client.newService(Http.scala:171)
	at wvlet.airframe.http.finagle.FinagleClient.<init>(FinagleClient.scala:122)
	at wvlet.airframe.http.finagle.FinagleClient$.newSyncClient(FinagleClient.scala:357)
	at wvlet.airframe.http.finagle.FinagleClientConfig.newSyncClient(FinagleClient.scala:97)
	at xerial.sbt.sonatype.SonatypeClient.<init>(SonatypeClient.scala:80)
	at xerial.sbt.Sonatype$.withSonatypeService(Sonatype.scala:395)
	at xerial.sbt.Sonatype$.$anonfun$sonatypeBundleRelease$1(Sonatype.scala:155)
	at sbt.Command$.$anonfun$command$2(Command.scala:97)
	at sbt.Command$.process(Command.scala:189)
	at sbt.MainLoop$.$anonfun$processCommand$5(MainLoop.scala:242)
	at scala.Option.getOrElse(Option.scala:189)
	at sbt.MainLoop$.process$1(MainLoop.scala:242)
	at sbt.MainLoop$.processCommand(MainLoop.scala:266)
	at sbt.MainLoop$.$anonfun$next$5(MainLoop.scala:162)
	at sbt.State$StateOpsImpl$.runCmd$1(State.scala:289)
	at sbt.State$StateOpsImpl$.process$extension(State.scala:325)
	at sbt.MainLoop$.$anonfun$next$4(MainLoop.scala:162)
	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:23)
	at sbt.MainLoop$.next(MainLoop.scala:162)
	at sbt.MainLoop$.run(MainLoop.scala:143)
	at sbt.MainLoop$.$anonfun$runWithNewLog$1(MainLoop.scala:118)
	at sbt.io.Using.apply(Using.scala:27)
	at sbt.MainLoop$.runWithNewLog(MainLoop.scala:111)
	at sbt.MainLoop$.runAndClearLast(MainLoop.scala:65)
	at sbt.MainLoop$.runLoggedLoop(MainLoop.scala:50)
	at sbt.MainLoop$.runLogged(MainLoop.scala:41)
	at sbt.StandardMain$.runManaged(Main.scala:191)
	at sbt.xMain$.$anonfun$run$8(Main.scala:102)
	at sbt.internal.util.Terminal$.withStreams(Terminal.scala:378)
	at sbt.xMain$.run(Main.scala:86)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at sbt.internal.XMainConfiguration.run(XMainConfiguration.scala:83)
	at sbt.xMain.run(Main.scala:46)
	at xsbt.boot.Launch$$anonfun$run$1.apply(Launch.scala:111)
	at xsbt.boot.Launch$.withContextLoader(Launch.scala:131)
	at xsbt.boot.Launch$.run(Launch.scala:111)
	at xsbt.boot.Launch$$anonfun$apply$1.apply(Launch.scala:37)
	at xsbt.boot.Launch$.launch(Launch.scala:120)
	at xsbt.boot.Launch$.apply(Launch.scala:20)
	at xsbt.boot.Boot$.runImpl(Boot.scala:56)
	at xsbt.boot.Boot$.main(Boot.scala:18)
	at xsbt.boot.Boot.main(Boot.scala)
Caused by: com.fasterxml.jackson.databind.JsonMappingException: Scala module 2.9.10 requires Jackson Databind version >= 2.9.0 and < 2.10.0
	at com.fasterxml.jackson.module.scala.JacksonModule.setupModule(JacksonModule.scala:61)
	at com.fasterxml.jackson.module.scala.JacksonModule.setupModule$(JacksonModule.scala:46)
	at com.fasterxml.jackson.module.scala.DefaultScalaModule.setupModule(DefaultScalaModule.scala:17)
	at com.fasterxml.jackson.databind.ObjectMapper.registerModule(ObjectMapper.java:817)
	at com.twitter.finagle.toggle.JsonToggleMap$.<init>(JsonToggleMap.scala:82)
	at com.twitter.finagle.toggle.JsonToggleMap$.<clinit>(JsonToggleMap.scala)
	... 59 more
[error] java.lang.ExceptionInInitializerError
```

Thanks.

**Comment by AlexITC** [comment]
Apparently this got fixed by upgrading the plugin, now my issue is that I'm not packaging any docs, and the publish task fails due to that, I'll open a separate ticket for it:

```
2020-12-19 20:41:29.014Z error [SonatypeClient] [close] Failed  - (SonatypeClient.scala:182)
2020-12-19 20:41:29.014Z error [SonatypeClient] Activity name:close, started:2020-12-19T20:41:04.901Z  - (SonatypeClient.scala:456)
2020-12-19 20:41:29.015Z error [SonatypeClient]     Failed: javadoc-staging, failureMessage:Missing: no javadoc jar found in folder '/com/alexitc/sjs-material-ui-facade_sjs1_2.13/0.1.1'  - (SonatypeClient.scala:375)
2020-12-19 20:41:29.017Z error [Sonatype] [STAGE_FAILURE] Failed to close the repository.  - (Sonatype.scala:405)```
