### ISSUE TITLE
java.lang.RuntimeException: Failure running 'gpg --batch --passphrase

### ISSUE THREAD

**Issue by bilal-fazlani** [olafurpg/sbt-ci-release#170]
When publishing a tagged version, its failing with following error. 
publishing snapshot version works for some reason.

build instance
https://github.com/bilal-fazlani/swiftbar4s/runs/1605661138?check_suite_focus=true

log

```bash
[error] java.lang.RuntimeException: Failure running 'gpg --batch --passphrase ***

[error]  --detach-sign --armor --use-agent --output /home/runner/work/swiftbar4s/swiftbar4s/swiftbar4s/target/scala-3.0.0-M3/scalabar_3.0.0-M3-0.0.3-beta.pom.asc /home/runner/work/swiftbar4s/swiftbar4s/swiftbar4s/target/scala-3.0.0-M3/scalabar_3.0.0-M3-0.0.3-beta.pom'.  Exit code: 2
[error] 	at scala.sys.package$.error(package.scala:30)
[error] 	at com.jsuereth.sbtpgp.CommandLineGpgSigner.sign(PgpSigner.scala:74)
[error] 	at com.jsuereth.sbtpgp.PgpSettings$.$anonfun$signingSettings$2(PgpSettings.scala:151)
[error] 	at scala.collection.TraversableLike.$anonfun$flatMap$1(TraversableLike.scala:292)
[error] 	at scala.collection.immutable.Map$Map4.foreach(Map.scala:431)
[error] 	at scala.collection.TraversableLike.flatMap(TraversableLike.scala:292)
[error] 	at scala.collection.TraversableLike.flatMap$(TraversableLike.scala:289)
[error] 	at scala.collection.AbstractTraversable.flatMap(Traversable.scala:108)
[error] 	at com.jsuereth.sbtpgp.PgpSettings$.$anonfun$signingSettings$1(PgpSettings.scala:146)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
[error] 	at sbt.std.Transform$$anon$4.work(Transform.scala:68)
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:282)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:23)
[error] 	at sbt.Execute.work(Execute.scala:291)
[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:282)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:265)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:64)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error] 	at java.lang.Thread.run(Thread.java:748)
[error] (scalabar / signedArtifacts) Failure running 'gpg --batch --passphrase ***


[error]  --detach-sign --armor --use-agent --output /home/runner/work/swiftbar4s/swiftbar4s/swiftbar4s/target/scala-3.0.0-M3/scalabar_3.0.0-M3-0.0.3-beta.pom.asc /home/runner/work/swiftbar4s/swiftbar4s/swiftbar4s/target/scala-3.0.0-M3/scalabar_3.0.0-M3-0.0.3-beta.pom'.  Exit code: 2
[error] Total time: 18 s, completed Dec 24, 2020 3:11:47 PM

Error: Process completed with exit code 1.

```

**Comment by bilal-fazlani** [comment]
It is working.
I had probably setup the secrets incorrectly.
