### ISSUE TITLE
Sonatype release fail: error reading '[stdin]': Inappropriate ioctl for device

### ISSUE THREAD

**Issue by nicolasfara** [olafurpg/sbt-ci-release#207]
I'm tring to publish my project to Sonatype, I setup the following env with appropriate values:
- `PGP_PASSPHRASE`
- `PGP_SECRET`
- `SONATYPE_PASSWORD`
- `SONATYPE_USERNAME`

but when the task `sbt ci-release` is executed, the following errors are reported:

<details><summary>Full log message</summary>

```
[info] welcome to sbt 1.5.5 (AdoptOpenJDK Java 1.8.0_292)
[info] loading settings for project ecscala-build from plugins.sbt ...
[info] loading project definition from /home/runner/work/ecscala/ecscala/project
[info] loading settings for project root from build.sbt ...
[info] looking for workflow definition in /home/runner/work/ecscala/ecscala/.github/workflows
[info] set current project to ecscala (in build file:/home/runner/work/ecscala/ecscala/)
[info] Setting Scala version to 3.0.1 on 3 projects.
[info] Reapplying settings...
[info] looking for workflow definition in /home/runner/work/ecscala/ecscala/.github/workflows
[info] set current project to ecscala (in build file:/home/runner/work/ecscala/ecscala/)
Running ci-release.
  branch=refs/tags/v0.1.0
gpg (GnuPG) 2.2.19
libgcrypt 1.8.5
Copyright (C) 2019 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Home: /home/runner/.gnupg
Supported algorithms:
Pubkey: RSA, ELG, DSA, ECDH, ECDSA, EDDSA
Cipher: IDEA, 3DES, CAST5, BLOWFISH, AES, AES192, AES256, TWOFISH,
        CAMELLIA128, CAMELLIA192, CAMELLIA256
Hash: SHA1, RIPEMD160, SHA256, SHA384, SHA512, SHA224
Compression: Uncompressed, ZIP, ZLIB, BZIP2
gpg: directory '/home/runner/.gnupg' created
gpg: keybox '/home/runner/.gnupg/pubring.kbx' created
gpg: /home/runner/.gnupg/trustdb.gpg: trustdb created
gpg: key 6352DC6A0078662D: public key "Nicolas Farabegoli <nicolas.farabegoli@gmail.com>" imported
gpg: key 6352DC6A0078662D/6352DC6A0078662D: error sending to agent: Inappropriate ioctl for device
gpg: error building skey array: Inappropriate ioctl for device
gpg: error reading '[stdin]': Inappropriate ioctl for device
gpg: import from '[stdin]' failed: Inappropriate ioctl for device
gpg: Total number processed: 0
gpg:               imported: 1
gpg:       secret keys read: 1
Tag push detected, publishing a stable release
[info] Defining Global / pgpSecretRing
[info] The new value will be used by Global / pgpStaticContext
[info] Reapplying settings...
[info] looking for workflow definition in /home/runner/work/ecscala/ecscala/.github/workflows
[info] set current project to ecscala (in build file:/home/runner/work/ecscala/ecscala/)
[info] Defining Global / pgpPublicRing
[info] The new value will be used by Global / pgpStaticContext
[info] Reapplying settings...
[info] looking for workflow definition in /home/runner/work/ecscala/ecscala/.github/workflows
[info] set current project to ecscala (in build file:/home/runner/work/ecscala/ecscala/)
[success] Total time: 0 s, completed Sep 17, 2021 4:38:12 PM
[info] Setting Scala version to 3.0.1 on 3 projects.
[info] Reapplying settings...
[info] looking for workflow definition in /home/runner/work/ecscala/ecscala/.github/workflows
[info] set current project to ecscala (in build file:/home/runner/work/ecscala/ecscala/)
[info] Wrote /home/runner/work/ecscala/ecscala/core/target/scala-3.0.1/ecscala_3-0.1.0.pom
[info] Main Scala API documentation to /home/runner/work/ecscala/ecscala/core/target/scala-3.0.1/api...
[info] Skipping unused scalacOptions: -Yexplicit-nulls
[warn] Setting -bootclasspath is currently not supported.
[warn] one warning found
[info] Main Scala API documentation successful.
[warn] versionScheme setting is empty; set `ThisBuild / versionScheme := Some("early-semver")`, `Some("semver-spec")` or `Some("pvp")`
[warn] so tooling can use it for eviction errors etc - https://www.scala-sbt.org/1.x/docs/Publishing.html
[error] gpg: no default secret key: No secret key
[error] gpg: signing failed: No secret key
[error] java.lang.RuntimeException: Failure running 'gpg --batch --passphrase *** --detach-sign --armor --use-agent --output /home/runner/work/ecscala/ecscala/core/target/scala-3.0.1/ecscala_3-0.1.0.pom.asc /home/runner/work/ecscala/ecscala/core/target/scala-3.0.1/ecscala_3-0.1.0.pom'.  Exit code: 2
[error] 	at scala.sys.package$.error(package.scala:30)
[error] 	at com.jsuereth.sbtpgp.CommandLineGpgSigner.sign(PgpSigner.scala:48)
[error] 	at com.jsuereth.sbtpgp.PgpSettings$.$anonfun$signingSettings$2(PgpSettings.scala:151)
[error] 	at scala.collection.TraversableLike.$anonfun$flatMap$1(TraversableLike.scala:293)
[error] 	at scala.collection.immutable.Map$Map4.foreach(Map.scala:493)
[error] 	at scala.collection.TraversableLike.flatMap(TraversableLike.scala:293)
[error] 	at scala.collection.TraversableLike.flatMap$(TraversableLike.scala:290)
[error] 	at scala.collection.AbstractTraversable.flatMap(Traversable.scala:108)
[error] 	at com.jsuereth.sbtpgp.PgpSettings$.$anonfun$signingSettings$1(PgpSettings.scala:146)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
[error] 	at sbt.std.Transform$$anon$4.work(Transform.scala:68)
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:282)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:23)
[error] 	at sbt.Execute.work(Execute.scala:291)
[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:282)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:265)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:64)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error] 	at java.lang.Thread.run(Thread.java:748)
[error] (core / signedArtifacts) Failure running 'gpg --batch --passphrase *** --detach-sign --armor --use-agent --output /home/runner/work/ecscala/ecscala/core/target/scala-3.0.1/ecscala_3-0.1.0.pom.asc /home/runner/work/ecscala/ecscala/core/target/scala-3.0.1/ecscala_3-0.1.0.pom'.  Exit code: 2
[error] Total time: 9 s, completed Sep 17, 2021 4:38:21 PM
```

</details>

**Comment by nicolasfara** [comment]
Fixed updating the plugin to the version `"1.5.7"`
