### ISSUE TITLE
gpg: gpg-agent is not available in this session

### ISSUE THREAD

**Issue by kubukoz** [olafurpg/sbt-ci-release#72]
Hi!

I had a working setup with sbt-ci-release, but since the last successful one I can't get a release to work because of:

> gpg: gpg-agent is not available in this session

This shows up as an error but doesn't stop the release. Here's what happens next:

```
[info] sonatypeProfileName = com.[secure]
[info] Preparing a new staging repository for [sbt-sonatype] sup 0.7.0-M1
[info] Reading staging repository profiles...
[info] Reading staging profiles...
[info] Found a staging repository [com[secure]-1092] status:open, profile:com.[secure](3cd6b19d807dd3) description: [sbt-sonatype] sup 0.7.0-M1
[info] Dropping staging repository [com[secure]-1092] status:open, profile:com.[secure](3cd6b19d807dd3) description: [sbt-sonatype] sup 0.7.0-M1
[info] Creating a staging repository in profile com.[secure] with a description key: [sbt-sonatype] sup 0.7.0-M1
[info] Dropped successfully: com[secure]-1092
[info] Created successfully: com[secure]-1093
[info] Uploading bundle /home/travis/build/[secure]/sup/target/sonatype-staging/0.7.0-M1 to https://oss.sonatype.org/service/local/staging/deployByRepositoryId/com[secure]-1093/
[info] Finished bundle upload: /home/travis/build/[secure]/sup/target/sonatype-staging/0.7.0-M1
[info] Closing staging repository [com[secure]-1093] status:open, profile:com.[secure](3cd6b19d807dd3) description: [sbt-sonatype] sup 0.7.0-M1
[info] Activity open started:2019-10-10T15:15:15.010Z, stopped:2019-10-10T15:18:05.143Z
[info] repositoryCreated: id:com[secure]-1093, user:[secure], ip:34.66.200.49
[error] java.io.IOException: Timed out
[error] 	at xerial.sbt.NexusRESTService.closeStage(NexusClient.scala:423)
[error] 	at xerial.sbt.NexusRESTService.closeAndPromote(NexusClient.scala:504)
[error] 	at xerial.sbt.Sonatype$.$anonfun$sonatypeBundleRelease$1(Sonatype.scala:152)
[error] 	at sbt.Command$.$anonfun$command$2(Command.scala:91)
[error] 	at sbt.Command$.process(Command.scala:181)
[error] 	at sbt.MainLoop$.processCommand(MainLoop.scala:151)
[error] 	at sbt.MainLoop$.$anonfun$next$2(MainLoop.scala:139)
[error] 	at sbt.State$$anon$1.runCmd$1(State.scala:246)
[error] 	at sbt.State$$anon$1.process(State.scala:250)
[error] 	at sbt.MainLoop$.$anonfun$next$1(MainLoop.scala:139)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
[error] 	at sbt.MainLoop$.next(MainLoop.scala:139)
[error] 	at sbt.MainLoop$.run(MainLoop.scala:132)
[error] 	at sbt.MainLoop$.$anonfun$runWithNewLog$1(MainLoop.scala:110)
[error] 	at sbt.io.Using.apply(Using.scala:22)
[error] 	at sbt.MainLoop$.runWithNewLog(MainLoop.scala:104)
[error] 	at sbt.MainLoop$.runAndClearLast(MainLoop.scala:59)
[error] 	at sbt.MainLoop$.runLoggedLoop(MainLoop.scala:44)
[error] 	at sbt.MainLoop$.runLogged(MainLoop.scala:35)
[error] 	at sbt.StandardMain$.runManaged(Main.scala:138)
[error] 	at sbt.xMain.run(Main.scala:89)
[error] 	at xsbt.boot.Launch$$anonfun$run$1.apply(Launch.scala:109)
[error] 	at xsbt.boot.Launch$.withContextLoader(Launch.scala:128)
[error] 	at xsbt.boot.Launch$.run(Launch.scala:109)
[error] 	at xsbt.boot.Launch$$anonfun$apply$1.apply(Launch.scala:35)
[error] 	at xsbt.boot.Launch$.launch(Launch.scala:117)
[error] 	at xsbt.boot.Launch$.apply(Launch.scala:18)
[error] 	at xsbt.boot.Boot$.runImpl(Boot.scala:56)
[error] 	at xsbt.boot.Boot$.main(Boot.scala:18)
[error] 	at xsbt.boot.Boot.main(Boot.scala)
[error] java.io.IOException: Timed out
[error] Use 'last' for the full log.
The command "sbt ci-release" exited with 1.
```

If you think this might have something to do with this plugin, or you have any tips, I'll be happy for any help 🙏 many thanks!

Here's the failed job: https://travis-ci.com/kubukoz/sup/jobs/243867491

**Comment by alexarchambault** [comment]
I don't think the "gpg: gpg-agent is not available in this session" is the culprit here. I've been having releases [go fine](https://travis-ci.org/alexarchambault/data-class/jobs/595647607) in spite of that. OTOH, Sonatype has been [extremely](https://status.maven.org/) [flaky](https://twitter.com/li_haoyi/status/1182023505954529280) recently.

**Comment by ChristopherDavenport** [comment]
Oh yeah, Sonatype has been all over the place recently.

**Comment by olafurpg** [comment]
Yeah, Sonatype has been very flaky recently. I've seen the same "gpg: gpg-agent is not available in this session" warning in logs for successful releases.

**Comment by olafurpg** [comment]
Thankfully, with the latest sbt-sonatype it's possible to restart the CI job to retry a failed release
