### ISSUE TITLE
feedback

### ISSUE THREAD

**Issue by MasseGuillaume** [olafurpg/sbt-ci-release#9]
I did not export LONG_ID and I had an invalid GPG_SECRET

```
[error] java.io.IOException: secret key ring doesn't start with secret key tag: tag 0xffffffff
[error]   at org.bouncycastle.openpgp.PGPSecretKeyRing.<init>(Unknown Source)
[error]   at com.jsuereth.pgp.SecretKeyRing$.load(SecretKeyRing.scala:49)
[error]   at com.jsuereth.pgp.SecretKeyRing$.load(SecretKeyRing.scala:45)
[error]   at com.jsuereth.pgp.StreamingLoadable.loadFromFile(StreamingLoadable.scala:11)
[error]   at com.jsuereth.pgp.StreamingLoadable.loadFromFile$(StreamingLoadable.scala:11)
[error]   at com.jsuereth.pgp.SecretKeyRing$.loadFromFile(SecretKeyRing.scala:45)
[error]   at com.jsuereth.pgp.PGP$.loadSecretKeyRing(package.scala:31)
[error]   at com.jsuereth.pgp.cli.PgpStaticContext.secretKeyRing(context.scala:27)
[error]   at com.jsuereth.pgp.cli.PgpStaticContext.secretKeyRing$(context.scala:27)
[error]   at com.typesafe.sbt.pgp.SbtPgpStaticContext.secretKeyRing(SbtPgpCommandContext.scala:9)
[error]   at com.jsuereth.pgp.cli.DelegatingPgpStaticContext.secretKeyRing(context.scala:34)
[error]   at com.jsuereth.pgp.cli.DelegatingPgpStaticContext.secretKeyRing$(context.scala:34)
[error]   at com.typesafe.sbt.pgp.SbtPgpCommandContext.secretKeyRing(SbtPgpCommandContext.scala:14)
[error]   at com.typesafe.sbt.pgp.BouncyCastlePgpSigner.$anonfun$sign$3(PgpSigner.scala:42)
[error]   at com.typesafe.sbt.pgp.Cache.withValue(SbtHelpers.scala:38)
[error]   at com.typesafe.sbt.pgp.Cache.withValue$(SbtHelpers.scala:36)
[error]   at com.typesafe.sbt.pgp.PasswordCache$.withValue(SbtHelpers.scala:55)
[error]   at com.typesafe.sbt.pgp.SbtPgpCommandContext.$anonfun$withPassphrase$1(SbtPgpCommandContext.scala:41)
[error]   at com.typesafe.sbt.pgp.SbtPgpCommandContext.retry(SbtPgpCommandContext.scala:49)
[error]   at com.typesafe.sbt.pgp.SbtPgpCommandContext.withPassphrase(SbtPgpCommandContext.scala:38)
[error]   at com.typesafe.sbt.pgp.BouncyCastlePgpSigner.sign(PgpSigner.scala:37)
[error]   at com.typesafe.sbt.pgp.PgpSettings$.$anonfun$signingSettings$2(PgpSettings.scala:157)
[error]   at scala.collection.TraversableLike.$anonfun$flatMap$1(TraversableLike.scala:241)
[error]   at scala.collection.immutable.Map$Map4.foreach(Map.scala:233)
[error]   at scala.collection.TraversableLike.flatMap(TraversableLike.scala:241)
[error]   at scala.collection.TraversableLike.flatMap$(TraversableLike.scala:238)
[error]   at scala.collection.AbstractTraversable.flatMap(Traversable.scala:104)
[error]   at com.typesafe.sbt.pgp.PgpSettings$.$anonfun$signingSettings$1(PgpSettings.scala:154)
[error]   at scala.Function1.$anonfun$compose$1(Function1.scala:44)
[error]   at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:39)
[error]   at sbt.std.Transform$$anon$4.work(System.scala:66)
[error]   at sbt.Execute.$anonfun$submit$2(Execute.scala:263)
[error]   at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
[error]   at sbt.Execute.work(Execute.scala:272)
[error]   at sbt.Execute.$anonfun$submit$1(Execute.scala:263)
[error]   at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:174)
[error]   at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
[error]   at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error]   at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error]   at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error]   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error]   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error]   at java.lang.Thread.run(Thread.java:748)
[error] java.io.IOException: secret key ring doesn't start with secret key tag: tag 0xffffffff
[error]   at org.bouncycastle.openpgp.PGPSecretKeyRing.<init>(Unknown Source)
[error]   at com.jsuereth.pgp.SecretKeyRing$.load(SecretKeyRing.scala:49)
[error]   at com.jsuereth.pgp.SecretKeyRing$.load(SecretKeyRing.scala:45)
[error]   at com.jsuereth.pgp.StreamingLoadable.loadFromFile(StreamingLoadable.scala:11)
[error]   at com.jsuereth.pgp.StreamingLoadable.loadFromFile$(StreamingLoadable.scala:11)
[error]   at com.jsuereth.pgp.SecretKeyRing$.loadFromFile(SecretKeyRing.scala:45)
[error]   at com.jsuereth.pgp.PGP$.loadSecretKeyRing(package.scala:31)
[error]   at com.jsuereth.pgp.cli.PgpStaticContext.secretKeyRing(context.scala:27)
[error]   at com.jsuereth.pgp.cli.PgpStaticContext.secretKeyRing$(context.scala:27)
[error]   at com.typesafe.sbt.pgp.SbtPgpStaticContext.secretKeyRing(SbtPgpCommandContext.scala:9)
[error]   at com.jsuereth.pgp.cli.DelegatingPgpStaticContext.secretKeyRing(context.scala:34)
[error]   at com.jsuereth.pgp.cli.DelegatingPgpStaticContext.secretKeyRing$(context.scala:34)
[error]   at com.typesafe.sbt.pgp.SbtPgpCommandContext.secretKeyRing(SbtPgpCommandContext.scala:14)
[error]   at com.typesafe.sbt.pgp.BouncyCastlePgpSigner.$anonfun$sign$3(PgpSigner.scala:42)
[error]   at com.typesafe.sbt.pgp.Cache.withValue(SbtHelpers.scala:38)
[error]   at com.typesafe.sbt.pgp.Cache.withValue$(SbtHelpers.scala:36)
[error]   at com.typesafe.sbt.pgp.PasswordCache$.withValue(SbtHelpers.scala:55)
[error]   at com.typesafe.sbt.pgp.SbtPgpCommandContext.$anonfun$withPassphrase$1(SbtPgpCommandContext.scala:41)
[error]   at com.typesafe.sbt.pgp.SbtPgpCommandContext.retry(SbtPgpCommandContext.scala:49)
[error]   at com.typesafe.sbt.pgp.SbtPgpCommandContext.withPassphrase(SbtPgpCommandContext.scala:38)
[error]   at com.typesafe.sbt.pgp.BouncyCastlePgpSigner.sign(PgpSigner.scala:37)
[error]   at com.typesafe.sbt.pgp.PgpSettings$.$anonfun$signingSettings$2(PgpSettings.scala:157)
[error]   at scala.collection.TraversableLike.$anonfun$flatMap$1(TraversableLike.scala:241)
[error]   at scala.collection.immutable.Map$Map4.foreach(Map.scala:233)
[error]   at scala.collection.TraversableLike.flatMap(TraversableLike.scala:241)
[error]   at scala.collection.TraversableLike.flatMap$(TraversableLike.scala:238)
[error]   at scala.collection.AbstractTraversable.flatMap(Traversable.scala:104)
[error]   at com.typesafe.sbt.pgp.PgpSettings$.$anonfun$signingSettings$1(PgpSettings.scala:154)
[error]   at scala.Function1.$anonfun$compose$1(Function1.scala:44)
[error]   at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:39)
[error]   at sbt.std.Transform$$anon$4.work(System.scala:66)
[error]   at sbt.Execute.$anonfun$submit$2(Execute.scala:263)
[error]   at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
[error]   at sbt.Execute.work(Execute.scala:272)
[error]   at sbt.Execute.$anonfun$submit$1(Execute.scala:263)
[error]   at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:174)
[error]   at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
[error]   at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error]   at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error]   at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error]   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error]   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error]   at java.lang.Thread.run(Thread.java:748)
[error] (structureJS / signedArtifacts) java.io.IOException: secret key ring doesn't start with secret key tag: tag 0xffffffff
[error] (structure / signedArtifacts) java.io.IOException: secret key ring doesn't start with secret key tag: tag 0xffffffff
[error] Total time: 24 s, completed Jun 22, 2018 1:47:22 PM
/home/travis/.travis/job_stages: line 190:  2801 Terminated              travis_jigger $! $timeout $cmd
```

I pushed a tag without the v as a prefix:

```
[error] java.io.IOException: PUT operation to URL https://oss.sonatype.org/content/repositories/snapshots/com/github/masseguillaume/scalameta-structure_sjs0.6_2.12/0.1.0/scalameta-structure_sjs0.6_2.12-0.1.0.pom failed with status code 400: Bad Request
[error]   at org.apache.ivy.util.url.AbstractURLHandler.validatePutStatusCode(AbstractURLHandler.java:82)
[error]   at sbt.internal.librarymanagement.ivyint.GigahorseUrlHandler.upload(GigahorseUrlHandler.scala:191)
[error]   at org.apache.ivy.util.url.URLHandlerDispatcher.upload(URLHandlerDispatcher.java:82)
[error]   at org.apache.ivy.util.FileUtil.copy(FileUtil.java:150)
[error]   at org.apache.ivy.plugins.repository.url.URLRepository.put(URLRepository.java:84)
[error]   at sbt.internal.librarymanagement.ConvertResolver$LocalIfFileRepo.put(ConvertResolver.scala:365)
[error]   at org.apache.ivy.plugins.repository.AbstractRepository.put(AbstractRepository.java:130)
[error]   at sbt.internal.librarymanagement.ConvertResolver$ChecksumFriendlyURLResolver.put(ConvertResolver.scala:117)
[error]   at sbt.internal.librarymanagement.ConvertResolver$ChecksumFriendlyURLResolver.put$(ConvertResolver.scala:104)
[error]   at sbt.internal.librarymanagement.ConvertResolver$$anonfun$defaultConvert$lzycompute$1$PluginCapableResolver$1.put(ConvertResolver.scala:164)
[error]   at org.apache.ivy.plugins.resolver.RepositoryResolver.publish(RepositoryResolver.java:216)
[error]   at sbt.internal.librarymanagement.IvyActions$.$anonfun$publish$5(IvyActions.scala:499)
[error]   at sbt.internal.librarymanagement.IvyActions$.$anonfun$publish$5$adapted(IvyActions.scala:498)
[error]   at scala.collection.TraversableLike$WithFilter.$anonfun$foreach$1(TraversableLike.scala:789)
[error]   at scala.collection.Iterator.foreach(Iterator.scala:944)
[error]   at scala.collection.Iterator.foreach$(Iterator.scala:944)
[error]   at scala.collection.AbstractIterator.foreach(Iterator.scala:1432)
[error]   at scala.collection.IterableLike.foreach(IterableLike.scala:71)
[error]   at scala.collection.IterableLike.foreach$(IterableLike.scala:70)
[error]   at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
[error]   at scala.collection.TraversableLike$WithFilter.foreach(TraversableLike.scala:788)
[error]   at sbt.internal.librarymanagement.IvyActions$.publish(IvyActions.scala:498)
[error]   at sbt.internal.librarymanagement.IvyActions$.$anonfun$publish$3(IvyActions.scala:144)
[error]   at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
[error]   at sbt.internal.librarymanagement.IvyActions$.withChecksums(IvyActions.scala:157)
[error]   at sbt.internal.librarymanagement.IvyActions$.withChecksums(IvyActions.scala:151)
[error]   at sbt.internal.librarymanagement.IvyActions$.$anonfun$publish$1(IvyActions.scala:144)
[error]   at sbt.internal.librarymanagement.IvyActions$.$anonfun$publish$1$adapted(IvyActions.scala:134)
[error]   at sbt.internal.librarymanagement.IvySbt$Module.$anonfun$withModule$1(Ivy.scala:243)
[error]   at sbt.internal.librarymanagement.IvySbt.$anonfun$withIvy$1(Ivy.scala:204)
[error]   at sbt.internal.librarymanagement.IvySbt.sbt$internal$librarymanagement$IvySbt$$action$1(Ivy.scala:70)
[error]   at sbt.internal.librarymanagement.IvySbt$$anon$3.call(Ivy.scala:77)
[error]   at xsbt.boot.Locks$GlobalLock.withChannel$1(Locks.scala:95)
[error]   at xsbt.boot.Locks$GlobalLock.xsbt$boot$Locks$GlobalLock$$withChannelRetries$1(Locks.scala:80)
[error]   at xsbt.boot.Locks$GlobalLock$$anonfun$withFileLock$1.apply(Locks.scala:99)
[error]   at xsbt.boot.Using$.withResource(Using.scala:10)
[error]   at xsbt.boot.Using$.apply(Using.scala:9)
[error]   at xsbt.boot.Locks$GlobalLock.ignoringDeadlockAvoided(Locks.scala:60)
[error]   at xsbt.boot.Locks$GlobalLock.withLock(Locks.scala:50)
[error]   at xsbt.boot.Locks$.apply0(Locks.scala:31)
[error]   at xsbt.boot.Locks$.apply(Locks.scala:28)
[error]   at sbt.internal.librarymanagement.IvySbt.withDefaultLogger(Ivy.scala:77)
[error]   at sbt.internal.librarymanagement.IvySbt.withIvy(Ivy.scala:199)
[error]   at sbt.internal.librarymanagement.IvySbt.withIvy(Ivy.scala:196)
[error]   at sbt.internal.librarymanagement.IvySbt$Module.withModule(Ivy.scala:242)
[error]   at sbt.internal.librarymanagement.IvyActions$.publish(IvyActions.scala:134)
[error]   at sbt.Classpaths$.$anonfun$publishTask$4(Defaults.scala:2244)
[error]   at sbt.Classpaths$.$anonfun$publishTask$4$adapted(Defaults.scala:2243)
[error]   at scala.Function1.$anonfun$compose$1(Function1.scala:44)
[error]   at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:39)
[error]   at sbt.std.Transform$$anon$4.work(System.scala:66)
[error]   at sbt.Execute.$anonfun$submit$2(Execute.scala:263)
[error]   at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
[error]   at sbt.Execute.work(Execute.scala:272)
[error]   at sbt.Execute.$anonfun$submit$1(Execute.scala:263)
[error]   at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:174)
[error]   at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
[error]   at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error]   at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error]   at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error]   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error]   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error]   at java.lang.Thread.run(Thread.java:748)
[error] java.io.IOException: PUT operation to URL https://oss.sonatype.org/content/repositories/snapshots/com/github/masseguillaume/scalameta-structure_2.12/0.1.0/scalameta-structure_2.12-0.1.0.pom failed with status code 400: Bad Request
[error]   at org.apache.ivy.util.url.AbstractURLHandler.validatePutStatusCode(AbstractURLHandler.java:82)
[error]   at sbt.internal.librarymanagement.ivyint.GigahorseUrlHandler.upload(GigahorseUrlHandler.scala:191)
[error]   at org.apache.ivy.util.url.URLHandlerDispatcher.upload(URLHandlerDispatcher.java:82)
[error]   at org.apache.ivy.util.FileUtil.copy(FileUtil.java:150)
[error]   at org.apache.ivy.plugins.repository.url.URLRepository.put(URLRepository.java:84)
[error]   at sbt.internal.librarymanagement.ConvertResolver$LocalIfFileRepo.put(ConvertResolver.scala:365)
[error]   at org.apache.ivy.plugins.repository.AbstractRepository.put(AbstractRepository.java:130)
[error]   at sbt.internal.librarymanagement.ConvertResolver$ChecksumFriendlyURLResolver.put(ConvertResolver.scala:117)
[error]   at sbt.internal.librarymanagement.ConvertResolver$ChecksumFriendlyURLResolver.put$(ConvertResolver.scala:104)
[error]   at sbt.internal.librarymanagement.ConvertResolver$$anonfun$defaultConvert$lzycompute$1$PluginCapableResolver$1.put(ConvertResolver.scala:164)
[error]   at org.apache.ivy.plugins.resolver.RepositoryResolver.publish(RepositoryResolver.java:216)
[error]   at sbt.internal.librarymanagement.IvyActions$.$anonfun$publish$5(IvyActions.scala:499)
[error]   at sbt.internal.librarymanagement.IvyActions$.$anonfun$publish$5$adapted(IvyActions.scala:498)
[error]   at scala.collection.TraversableLike$WithFilter.$anonfun$foreach$1(TraversableLike.scala:789)
[error]   at scala.collection.Iterator.foreach(Iterator.scala:944)
[error]   at scala.collection.Iterator.foreach$(Iterator.scala:944)
[error]   at scala.collection.AbstractIterator.foreach(Iterator.scala:1432)
[error]   at scala.collection.IterableLike.foreach(IterableLike.scala:71)
[error]   at scala.collection.IterableLike.foreach$(IterableLike.scala:70)
[error]   at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
[error]   at scala.collection.TraversableLike$WithFilter.foreach(TraversableLike.scala:788)
[error]   at sbt.internal.librarymanagement.IvyActions$.publish(IvyActions.scala:498)
[error]   at sbt.internal.librarymanagement.IvyActions$.$anonfun$publish$3(IvyActions.scala:144)
[error]   at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
[error]   at sbt.internal.librarymanagement.IvyActions$.withChecksums(IvyActions.scala:157)
[error]   at sbt.internal.librarymanagement.IvyActions$.withChecksums(IvyActions.scala:151)
[error]   at sbt.internal.librarymanagement.IvyActions$.$anonfun$publish$1(IvyActions.scala:144)
[error]   at sbt.internal.librarymanagement.IvyActions$.$anonfun$publish$1$adapted(IvyActions.scala:134)
[error]   at sbt.internal.librarymanagement.IvySbt$Module.$anonfun$withModule$1(Ivy.scala:243)
[error]   at sbt.internal.librarymanagement.IvySbt.$anonfun$withIvy$1(Ivy.scala:204)
[error]   at sbt.internal.librarymanagement.IvySbt.sbt$internal$librarymanagement$IvySbt$$action$1(Ivy.scala:70)
[error]   at sbt.internal.librarymanagement.IvySbt$$anon$3.call(Ivy.scala:77)
[error]   at xsbt.boot.Locks$GlobalLock.withChannel$1(Locks.scala:95)
[error]   at xsbt.boot.Locks$GlobalLock.xsbt$boot$Locks$GlobalLock$$withChannelRetries$1(Locks.scala:80)
[error]   at xsbt.boot.Locks$GlobalLock$$anonfun$withFileLock$1.apply(Locks.scala:99)
[error]   at xsbt.boot.Using$.withResource(Using.scala:10)
[error]   at xsbt.boot.Using$.apply(Using.scala:9)
[error]   at xsbt.boot.Locks$GlobalLock.ignoringDeadlockAvoided(Locks.scala:60)
[error]   at xsbt.boot.Locks$GlobalLock.withLock(Locks.scala:50)
[error]   at xsbt.boot.Locks$.apply0(Locks.scala:31)
[error]   at xsbt.boot.Locks$.apply(Locks.scala:28)
[error]   at sbt.internal.librarymanagement.IvySbt.withDefaultLogger(Ivy.scala:77)
[error]   at sbt.internal.librarymanagement.IvySbt.withIvy(Ivy.scala:199)
[error]   at sbt.internal.librarymanagement.IvySbt.withIvy(Ivy.scala:196)
[error]   at sbt.internal.librarymanagement.IvySbt$Module.withModule(Ivy.scala:242)
[error]   at sbt.internal.librarymanagement.IvyActions$.publish(IvyActions.scala:134)
[error]   at sbt.Classpaths$.$anonfun$publishTask$4(Defaults.scala:2244)
[error]   at sbt.Classpaths$.$anonfun$publishTask$4$adapted(Defaults.scala:2243)
[error]   at scala.Function1.$anonfun$compose$1(Function1.scala:44)
[error]   at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:39)
[error]   at sbt.std.Transform$$anon$4.work(System.scala:66)
[error]   at sbt.Execute.$anonfun$submit$2(Execute.scala:263)
[error]   at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
[error]   at sbt.Execute.work(Execute.scala:272)
[error]   at sbt.Execute.$anonfun$submit$1(Execute.scala:263)
[error]   at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:174)
[error]   at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
[error]   at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error]   at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error]   at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error]   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error]   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error]   at java.lang.Thread.run(Thread.java:748)
[error] (structureJS / publish) java.io.IOException: PUT operation to URL https://oss.sonatype.org/content/repositories/snapshots/com/github/masseguillaume/scalameta-structure_sjs0.6_2.12/0.1.0/scalameta-structure_sjs0.6_2.12-0.1.0.pom failed with status code 400: Bad Request
[error] (structure / publish) java.io.IOException: PUT operation to URL https://oss.sonatype.org/content/repositories/snapshots/com/github/masseguillaume/scalameta-structure_2.12/0.1.0/scalameta-structure_2.12-0.1.0.pom failed with status code 400: Bad Request
[error] Total time: 31 s, completed Jun 22, 2018 2:15:07 PM
/home/travis/.travis/job_stages: line 190:  2712 Terminated              travis_jigger $! $timeout $cmd
```

Add command for tag/push

```
git tag v0.1.0
git push --tag
```

Add full .travis.yml file

```yml
language: scala
jdk:
- oraclejdk8

stages:
  - name: test
  - name: release
    if: (branch = master AND type = push) OR (tag IS present)

jobs:
  include:
    - env: TEST="test"
      script: sbt test
    - stage: release
      script: travis_wait 60 sbt ci-release

cache:
  directories:
    - $HOME/.sbt/1.0/dependency
    - $HOME/.sbt/boot/scala*
    - $HOME/.sbt/launchers
    - $HOME/.ivy2/cache
    - $HOME/.coursier

before_cache:
  - du -h -d 1 $HOME/.ivy2/cache
  - du -h -d 2 $HOME/.sbt/
  - find $HOME/.sbt -name "*.lock" -type f -delete
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -type f -delete
  - rm -rf $HOME/.ivy2/local

before_install:
  - git fetch --tags
```

**Comment by olafurpg** [comment]
Thanks for the feedback! I opened https://github.com/olafurpg/sbt-ci-release/pull/10 to update the readme to address the problems you encountered.
